project:
  type: website
  output-dir: docs

website:
  title: "Nibia"
  navbar:
    left:
      - href: index.qmd
        text: Inicio/Home
      - href: about.qmd
        text: Sobre mi/About

      - text: Projects/Proyectos
        menu:
          - href: projects.qmd
            text: Projects Overview
    right:
      - icon: envelope
        href: "mailto:nibiab.work@gmail.com"
      - text: LinkedIn
        icon: linkedin
        href: "https://www.linkedin.com/in/nibia-becerra-santillan/"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



